import { useState } from "react";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <Card1 />
      <Card2 />
      <Card3 />
      <Card4 />
      <Card5 />
    </div>
  );
}

function Card1() {
  return (
    <div className="div1">
      <div style={{ marginTop: "50px" }}>
        <span className="spa">home</span>
        <span className="span">about</span>
        <span className="span">hours</span>
        <span className="span">products</span>
        <span className="span">contact</span>
        <img
          className="img1"
          src={
            "https://images.squarespace-cdn.com/content/v1/5be5079c8ab722cec6281db7/1554667269655-BAGF41731E71656FQBCS/cleenland-logo-rgb-main-lockup-black%40300x.png?format=500w"
          }
        />
        <span className="span">thoughts</span>
        <span className="span">product instructions</span>
        <span className="span">grab an e-gift card</span>
      </div>
      <div className="div2">cleaning up a dirty world</div>
    </div>
  );
}
function Card2() {
  return (
    <div className="div1">
      <div className="div3">
        Cleenland is your one-stop shop for low-waste, refillable personal and
        home care supplies.
      </div>
      <div className="div4">
        We also have reusable bottles, low-waste personal and home care
        accessories, and smiles to go around.
      </div>
      <div style={{ display: "flex", marginBottom: "100px" }}>
        <div className="div5">
          Current mask policy: Masks are optional for now. Still, we aim to
          ensure everyone can shop with us comfortably while reducing waste
          generated by masks worn only once. If you would be more comfortable in
          a masked environment, please let us know — staff will happily mask and
          distribute masks to other visitors. This is a genuine offer — please
          take us up on it! Thank you for visiting Cleenland! (Updated 4/28/24)
        </div>
        <div>
          <img
            className="img2"
            src={
              "https://images.squarespace-cdn.com/content/v1/5be5079c8ab722cec6281db7/1585003575777-YB6ZQPIQWE7H142II2MD/cleenland-logo-monogram-rgb-yellow-xs.png?format=1000w"
            }
          />
        </div>
      </div>
    </div>
  );
}
function Card3() {
  return (
    <div className="div1">
      <div
        style={{
          fontWeight: "800",
          textAlign: "center",
          letterSpacing: "2px",
          fontSize: "30px",
        }}
      >
        Stay tuned.
      </div>
      <div
        style={{ textAlign: "center", marginTop: "30px", letterSpacing: "2px" }}
      >
        Be the first to hear about Cleenland’s newest product.
      </div>
    </div>
  );
}
function Card4() {
  const [showSignUpCard, setShowSignUpCard] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);

  const handleSignUp = () => {
    setShowSignUpCard(true);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    setIsSubmitted(true);
    setShowSignUpCard(false);
    alert("You are signed in!");
  };

  const handleCloseCard = () => {
    setShowSignUpCard(false);
  };

  return (
    <div>
      {!isSubmitted && (
        <button className="button1" onClick={handleSignUp}>
          SignUp
        </button>
      )}
      {showSignUpCard && (
        <div className="SignUp">
          <h2>Sign Up</h2>
          <form onSubmit={handleSubmit}>
            <div>
              <label>Username: </label>
              <input type="text" placeholder="Enter your username" required />
            </div>
            <div>
              <label>Email ID: </label>
              <input type="email" placeholder="Enter your email" required />
            </div>
            <div>
              <label>Phone Number:</label>
              <input
                type="tel"
                placeholder="Enter your phone number"
                required
              />
            </div>
            <button type="submit">Submit</button>
          </form>
          <button onClick={handleCloseCard}>Close</button>
        </div>
      )}
    </div>
  );
}
function Card5() {
  return (
    <div>
      <div className="do">Don’t worry — we’ll keep your inbox clean.</div>
      <div
        style={{
          textAlign: "center",
          lineHeight: "30px",
        }}
      >
        <div>A low-waste, no-shame store.</div>
        <div>89A Norfolk Street, Cambridge, MA 02139</div>
        <div>857-228-4595</div>
        <div>wassup@cleenland.com</div>
      </div>
      <div>
        <img
          className="imag"
          src={
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAY1BMVEX///8AAADz8/P7+/uQkJCHh4d1dXWvr6/v7++ysrKDg4Po6Oj4+PiNjY16enrOzs7V1dXc3Nw1NTXFxcUgICARERFdXV0oKCigoKBnZ2eYmJi9vb1GRkZYWFhSUlI6OjoYGBhp1j93AAAKCklEQVR4nO1de5+qLBDetPWG18xCLev7f8q33N2zzSDIgNL5ndfn3wx5BIa5MXx8bNiwYcOGDRs2bNiwYcP/HP4D6QiPgucfHv98d++f8FMvihiryrKo+z7mnHf7LEseyH8QTOP5U5JkWcd52Pd1UZYsiiIvfQ+t1GOsjHl+ORx3y+B4GHLeVyxK3TLxojL+PCxEAqPlBfNcjVDKiu6yEpFvnPOaeQ6oRCVfa0gA7vsyWnl4oiJpXFAZEdRr0vGKwBmTEac6WolKWn26G5VvNEm1imyL4ptrKk8cwuUHx6/yd1B5Iq8WXjl+cX0Xl91uKBZlk/YrbyxqXPoFF473nuXyi0O4GBsvdLJNOmGTKrk058NluF5P7QPf2vCoEH/jU4Yfzfrxn8c/T9fhcjgrJP8tXoSNL18vl2ub7x8qfFFVD2U3MtQOfW+0IvqQZ0E7yHTwS7+EFCiGycaPQ5D15dLaICt4fpqeCNfCvvmqnfxOAV9WXr6+Mcwnv1/LbFuOPqeo5P2qCrpfJFN09pYv9cOz0OY5qJfpswpFIk62c2zXZilu/AN3YTY9ZKj46rayadHbiw0usA71UIqrtbORz7Ww8wdWH4cGJui2F4svKa7+fC1jafr9AhsLGVDjRZhbS0caGLZsb8ZDI6wYe0lPRXVCXeCmq6ZAeozNjDUF7sO1NGvHD2E7zTK6ngJlzzkP69fxT1EndoZ7TYUm7NoLpuLXUcs8BPGLmMHLJjHrRX0HrRxW3vfr322lyV42gBrqIAejuY5nWbauVC6A5HyZBSxZYJ6h8T2uOzAeXOhN9vtTD222T5N5Bj/VLlh3xWTw879OamSEDCbyrIeth8t1fALpDiP4/Y3DXwymiAebMN96tVALZIbfmYBEQEi3CtGSWVkui9r5TTrPDCRRCVekweegQIwuHH7ntdeBXwysGjTw/ZJdFzFB5kUEx/AX+oyHZEzVMq8q+pCPeHqkpAo8/Pb4jWjRkCWAD7+GiU0WFWGWt8PtfG8euJ9vQ5tkYTE540uBzPBCvIS6M5kMmqd76qLz6i64Tjj0ztegqycUVvxck7/8iExO8vpl0MjktP9XPL9Ifa3NJefCQGPl+Pa6NaIv21HNTSSZSVtm1Z1mEh2ObYfpQPF75OBHuOeRZTMy8QjCjHUnqG5P4n7q4M7FXl/YoI8Px42851Vgmznrr7m41aAy0mmh/lv9TuwzjmNCaUS23kvgZNK2ZVhCCEvd4CeO6q8MlqErsYTowbS9UkVrCXTmmyaZGvsfZnCC7bKy6Cd3I7jRXKh6cwH/rrdncnK08MbnW/3APq8bmQwYWD0bIhOd7LM477XIwElPJgO2CS0HT26Uv3HP51tGDqczVbeCqpmOomqc9JBokAHhmiOVDLQzNcggt8OybGBkpbEjM69nitbVH1yubRC0V0VaRDdLBkpJOzKze24sWS9XXpcVG1GVNZdI7mbOfYRsTaraTCNTTepiN17C5ESPldPS+zgz8si5SrQUkTnzOaPaTfXwFk+lWXpsMnXlpm4f2QCrkplY/EfOJG72lPGJcVQLgUXJqJXuSuzbUCgiBmk5ERhXTjTkol2TjDBvmmRmWkZi2qpyoiEyRHczhQx8dPfM4p0N5KR7wVBQ9dDdyOAVcNQJ1aUdZnNXPI0ixTHNiEdkVEFebL03idar/AzPNMXQWJKBXVSRwapyq/kmH+csHN9PpkBdOmh7GzwsOORaSgQjHquRQVKW4C3AjsrdIH3SERkP9qcJZA9OIUDLRvoWR2TQ8tefZGMfUQaIVAQ4IgP14EbD0HoFOlxwkj3niAzszZno0WJw1TSy59yQQd77lvSSD+yU3clcDW7IQCfwkRySgt69nczx5IYMXDJn0jtGQBEgWzQov2olMlDBkm8UUsBt6i556g1kmlnHhAgOJMhd8hQiQ4w2aZJhgIxJRkoNFs1dIg2dkCnBd6UK5iegcG4k4swJGejEPRsk16WQjETXdEKmhmSIREZAMpKJ6oQM9P0diDxGANks8wZuZP7g/zjN/ikB8E+J5n9q00TqjF60FaBzoc5o+s3eo2iuRAaaAAayGZqamiaAHRmpe3Zh40ymdrsh48hsdkPGd+PQcEMGu5o+SW/5SDRdTY7IYCcgKUlP2wnoiIwb96wjMoLjnJBwoO84d0VGCGloTzQ8yRQhjUXJqELnOApoHGxSWBDOyAhhwEwvDChU5FFk6Fr6zQhJDWYBWiGzQREFtHTPotwZ5RE8MXQ+f56aGDq3JAN7qD5PKCbDLJ3U4G5k6OkmU2U5lOkmi5KZSdFaPRHILnROzDdbO0ULkaFaGrS0xrWT51CKFvXcKTF7VpbWeIJpjZJSXLNpjXb5ZkhLOc3mNc8nnCqy0WcTte3SGulJ2qumAtuSgenzGrqwcZK2Rsq5ZfaswcEGs6KUWnkQlknaJkdO1jvYUNqlzxsdBuLkYnuaR04sDzaURse0CrvDQFJYHjmpwCzV9u6xnHJMS7sehuVhIAblh/6e2+seoDu2+o1Cb8FAPXOGD60S/ql5tJETHIaw8sSJSgYp3aRgRdW1M4dOzyfh0KkS0DQnV8CwO4FLPw6shA/98+SSIL7lodVUclD7+DyoTT2bHEHNj3y2GanN85qmCK8Is+TPEfqj8gi9Gkg1o9pmmAwlw/cVqWZxAzVQ9Sl6X1DZGcvagnZAVWPoZJCiSp+nywGtX/JpYEE22xVKtAPa8wxqE6HPYbpolgBaMialL1GtFuP6dfZALlOTqjHoYNj75hmqgGFU4AyVBGlWLqMjB8xIMSznhUbXsH6dNZAkMiy0hHaad4kAVMzzbtYNXL9u5XJtsl4gr49pvVgceFmuBLw+UuwrNS3nhQ+6/g1FQY37gOvX0U08azAcxTWvpFtg74TzQrrYTWpRzFOsPf3uEsdzZ/lVwDPW7djgerH6xXwmkYoV4VrDsrx0FGJZ8MzKEBHqJe92VzcSOpqITJnWN/5BLDrDD7kDXaAOxBcfbUtGTtSf3+2GZLXrGr5e2udTLnib1f8FQdJ/0cnDtfYcv+TBZDRhCSNEcsHR4ZTzYmnR5pV9Nulu2+lF72Yhv7LlOLRBxsMxnmx+X4sXsaoaPVL7XBHGXebKFvVlOl936ZxebtJR3aDz+XPHzu/9lO14lc7cXTrLXQ30V1xztJirS33RkQPc4gXddv/S1WBvvrTtuviuJl454gr5Cjta9J6Fc4tXsTrSyuHFoN+4Z+tcQfnxrEFKjPPbIihWDD74UT2pqq2CJjGJstHolEKRpVVw4KULE91jdW6Q8kPBpStk+aqLw/dYwdeab4fPuIwcx+nSiLGe58OCt4Nfch6XjHnviQSN97ZH7Ova9pDz7nlp+8xt7X8uqMyyfcc5j7+ubX9aEW+7tx3B9/30AY+CdMTjn38Fgw0bNmzYsGHDhg0bNmx4J/4Do3GrJfhS8GMAAAAASUVORK5CYII="
          }
        />
        <img
          className="imagee"
          src={
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAclBMVEX///8AAADx8fGxsbH39/e+vr6KioopKSkoKCj7+/vg4OBAQECNjY0JCQkNDQ1aWlpfX19LS0tGRkbp6enQ0NCDg4OhoaEjIyPb29urq6vm5uaamprDw8MwMDBubm4dHR02NjaVlZVUVFR3d3dmZmYVFRV4y9GXAAAC9klEQVR4nO3dC3LaMBRGYTAmwUB4Q3iEJqFk/1tshnZSaKfgK1+k3+45C2D0zYAsGyFarbQVeb+7GU6mg/3rqP3V00WjU7P3IvFY7WWL3bfXdvl689QjNtVfTUe3UZcdUw+6fPPVm1V3Kks98JItxkG8z15SD71MRWcW6mu3u6lHX6LuY7ivDsL+tIpPX5gvq/nkhet9VaC4cFXZpy3MJw5AZWE28AAKC+fPLkBdYd/Hpyt0A6oKs17ThT6TjLDw6AfUFO4cgZLCtSdQUhh2L18jYeW7CXWh73tUUXhouvDFGagn9J1mBIUdb6Cc0G89Kip0/xTKCYOfbNdFuPUHigkfGi90v1SoCb0XbHrC98YLHZ9daArvMZNqCf1XbGpC51vfX61Ts85yeoz/R3lq1ll3Aa5Sq85a3AM4TK06L3yieR4cjsuHvxtu+qlRF4VNNOPOQumTdrWQO6el0kx5s4Bldy32O31VmC8WH9vUY7ZlX7MprVbKZL51mqQesTWzsF4fwlbABT/1gM1Zhd9TD9icVbhLPWBzXaOwbjOpfVmqteQsk1VYlx3qv0OIUD+ECPVDiFA/hAj1Q4hQP4QI9UOIUD+EdRDm2ZXyjVG4vfZqP4t8OM38+GE0VO4t6ncbfj97tXSIKKxwOkmV4m2JmqcBtqfRhHf4IUWp9tFmG+u3g171om2YQogQ4f8rfESIECFChAgRIkSIECFChAgRIkSIECFChAgRIkSIsHbC5u9UyBIJI24Zqvh/OKFt4gnT7PoaxwN+vk89D8sv1yj6MVhF/u8K6+7L+bVXOxWbd6sm7KC9HkKE+iFEqB9ChPohRKgfQoT6IUSoH0KE+iFEqB9ChPohRKgfQoT6IUSoH0KE+iFEqB9ChPohRKgfQoT6IUSoH0KE+iFEqB9ChPohRKgfQoT6IUSoH0KE+iFEqB9ChPohRKgfQoT6IUSoX/OF1nN46ydc24Cz1OMNaGASRj+a1CHTKbVRD5d1K1vuy/GeZnc+HvgHllpO87YiSVIAAAAASUVORK5CYII="
          }
        />
      </div>
    </div>
  );
}

export default App;
